### ISSUE TITLE
Create CF template for spinning up the stack

### ISSUE THREAD

**Issue by joshmcfarlane** [ColectivaLegal/ScalaSmsAlertSystem#10]
This would create the RDS database, ELB, and spin up the EC2 instances or any other related resources needed to run the service.

**Comment by ErrorsAndGlitches** [comment]
Completed with code push:

https://github.com/ColectivaLegal/sms-alert-system-cloud-formation/commit/f7850e7eb67a716df99fe11c747940dbc74087d8
