### ISSUE TITLE
Move message sending to SNS

### ISSUE THREAD

**Issue by joshmcfarlane** [ColectivaLegal/ScalaSmsAlertSystem#5]
Twilio for long phone numbers currently throttles at about 1 message / second. We should swap out the message sending for SNS instead similar to the Django implementation.

**Comment by dougcole** [comment]
Planning to tackle this, but after #34. If this becomes a blocker please ping me.

**Comment by ErrorsAndGlitches** [comment]
Merged: 240842292e7dd3db3f719dbb8d09181bddd85ea6
