### ISSUE TITLE
Add AuthN around web portal

### ISSUE THREAD

**Issue by joshmcfarlane** [ColectivaLegal/ScalaSmsAlertSystem#7]
Add authentication around the web portal so only registered users can access it.

**Comment by joshmcfarlane** [comment]
http://www.securesocial.ws looks promising for integrating with Play and supporting local user/pass.

**Comment by joshmcfarlane** [comment]
Turns out securesocial hasn't been updated in a while and isn't compatible with the current version of Play.

**Comment by joshmcfarlane** [comment]
Played around with a few other frameworks, but nothing quite met the requirements or felt secure to use for user/pass auth. Came across Auth0 (https://auth0.com) which seems like it would plug in nice. Going to ping on Slack to see if it'd be worth building in vs rolling our own.

**Comment by ErrorsAndGlitches** [comment]
merged: 123c1acc05c7471355c3c4d6cd013498bd2ea48c
